Mark libext2_blkid as vendor available
error: system/core/fs_mgr/Android.bp:139:1: dependency "libext2_blkid" of "libfstab" missing variant:
  arch:android_arm64_armv8-a, image:vendor, link:static, version:

Change-Id: I74901487fb973741f395a4e90cbaafd96275d764
(cherry picked from commit 11a2e3e3c23989d042d03639324ebee3a36c90be)